name: json_serializable_e2e_test
description: e2e tests for fic/json_serializable

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  fast_immutable_collections:
    path: ../
  json_annotation: ^4.1.0

dev_dependencies:
  build_runner: ^2.1.2
  json_serializable: ^6.3.2
  lint: ^2.0.1
  test: ^1.17.12

publish_to: none

