name: benchmark_app
description: The example project for the fast_immutable_collections package.
publish_to: "none"
version: 0.0.1

environment:
  flutter: ">=2.0.0 <=3.0.0"
  sdk: '>=3.0.0 <4.0.0'

flutter:
  uses-material-design: true

dependencies:
  charts_flutter: ^0.12.0
  fast_immutable_collections_benchmarks:
    path: ../
  flutter:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  lint: ^2.0.1
